Clear state on decrypt password page issue77
frankhart2018/primistore pull request #81
Opened 2024-05-11 16:57 UTC by SumitKumar-17

### Clear state on decrypt password page  with reference to issue 77

To clear the previous decrypted data from state when the component mounts, you can add a cleanup function in the useEffect hook with an empty dependency array []. Here's how you can modify your useEffect hook:By dispatching decryptPasswordThunk({ passUid, pmsFile: null }), you're effectively clearing the decrypted data when the component mounts.

2024-05-11 23:40 UTC, frankhart2018 approved these changes

2024-05-11 23:40 UTC, frankhart2018 commented on frontend/src/components/pages/DecryptPassword/DecryptPassword.js
> +    dispatch(decryptPasswordThunk({ passUid, pmsFile: null }));
Why does the API need to be called?

2024-05-11 23:44 UTC, frankhart2018 requested changes
Please make the required changes. s

2024-05-12 16:07 UTC, frankhart2018 requested changes
There are merge conflicts. Please resolve those.

2024-05-12 16:50 UTC, SumitKumar-17 commented
@frankhart2018  Completed the merge conflicts.

2024-05-12 17:18 UTC, frankhart2018 commented
Did you actually change anything? I still see a call to the thunk that calls the API.

2024-05-12 17:24 UTC, SumitKumar-17 commented
@frankhart2018  No, I didn't change anything in my code as I gave you the first time. You had asked me about details of what I had done. I explained it above.
After that further, I had just resolved only merge conflicts due to the latest updates in the master branch

2024-05-12 17:34 UTC, frankhart2018 commented
> @frankhart2018 No, I didn't change anything in my code as I gave you the first time. You had asked me about details of what I had done. I explained it above. After that further, I had just resolved only merge conflicts due to the latest updates in the master branch

The question was rhetorical. The answer is no it does not need to call the API and hence does not need to call the thunk. Please fix that.

2024-05-12 17:34 UTC, closed without merging